name: sentinel-2-l2a
title: Sentinel-2 L2A
collection: sentinel-2-l2a
url: https://earth-search.aws.element84.com/v1
assets:
- name: coastal
- name: blue
- name: green
- name: red
- name: rededge1
- name: rededge2
- name: rededge3
- name: nir
- name: nir08
- name: nir09
- name: swir16
- name: swir22
- name: scl
  bands: 
  - name: scl
    description: "Scene classification map (SCL)"
    values:
      0: NO_DATA
      1: SATURATED_OR_DEFECTIVE
      2: CAST_SHADOWS
      3: CLOUD_SHADOWS
      4: VEGETATION
      5: NOT_VEGETATED
      6: WATER
      7: UNCLASSIFIED
      8: CLOUD_MEDIUM_PROBABILITY
      9: CLOUD_HIGH_PROBABILITY
      10: THIN_CIRRUS
      11: SNOW or ICE